project:
  type: website
  output-dir: docs

website:
  title: "Nicolás Rojo"
  navbar:
    background: "#ffffff"
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/siempretupido
      - icon: linkedin
        href: https://www.linkedin.com/in/nicol%C3%A1s-r-2909a3268/

format:
  html:
    theme: cosmo
    css: styles.css
    # Añadimos los archivos de Google Tag Manager aquí:
    include-in-header: 
      - aos-head.html
      - gtm-head.html
    include-before-body: 
      - sc-visuals.html
      - gtm-body.html
